matrix:
  include:
    - language: rust
      rust:
        - nightly
      cache: cargo
      script:
        - cargo build --verbose --all
    - language: node_js
      node_js:
        - 8.12
      cache: yarn
      before_install:
        - cd app
      install:
        - yarn install
      script:
        - yarn build