matrix:
  include:
    - language: rust
      cache: cargo
      before_script:
        - rustup toolchain install nightly
      script:
        - cargo +nightly build --all --release
    - language: node_js
      node_js:
        - 8.12
      cache: yarn
      before_install:
        - cd app
      install:
        - yarn install
      script:
        - yarn test
        - yarn build